name: push-image

on:
  push:
    tags:
      - '*.*.*'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: get release version
        id: release_version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: docker build
        run: docker build -t ${IMG} .
        env:
          IMG: kubechamp/terraform-operator:${{ steps.release_version.outputs.tag }}

      - name: docker push
        run: docker push ${IMG}
        env:
          IMG: kubechamp/terraform-operator:${{ steps.release_version.outputs.tag }}

